### ISSUE TITLE
How can I automatically upload the zim file?

### ISSUE THREAD

**Issue by k3vin6793** [kiwix/kiwix-html5#186]

**Comment by kelson42** [comment]
Which ZIM file do you want to upload?
To where do you exactly want to upload this ZIM file?

**Comment by mossroy** [comment]
I suppose you open kiwix-html5 in a desktop browser, and want to avoid having to manually select the ZIM file(s) from the User Interface each time you open the application? So that it remembers the selected ZIM file(s) next time you run it?
This is unfortunately not possible for now in a standard page of a desktop browser. Because a browser will not allow to open a local file that has not been manually selected (for security reasons).

There are discussions to allow this in a WebExtension, but it's not decided yet, and apparently far from being implemented for now. See https://bugzilla.mozilla.org/show_bug.cgi?id=1246236

It was possible on Firefox OS because it implemented the (now obsolete) [DeviceStorage API](https://developer.mozilla.org/en-US/docs/Web/API/DeviceStorage).
