### ISSUE TITLE
Discrepancy in version numbers with FF extension

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-html5#235]
* FF extension manager says Kiwix extension is version 2.0.0
* Kiwix extension itselfs says it is Kiwix 2.0commit-bbe7610

Might be better that both agree (and avoid git version name on official releases).

**Comment by mossroy** [comment]
Are you sure you're not still using a nightly build?
I tried again to uninstall the extension, install it from the addon manager of Firefox (not with an xpi) : I see 2.0.0 everywhere, as expected.

In nightly builds, I put the git commit short id in Kiwix UI (so that we know which version we test). But I can not put it in the manifest.json (which is used by Firefox and Chrome), because Chrome does not allow it : https://developer.chrome.com/extensions/manifest/version

**Comment by kelson42** [comment]
My error, sorry.
